com.he.springBoot:
  title: 蟑螂恶霸
  content: 324
logging:
  path: /tmp/log
  level:
    com.he.springBoot: DEBUG
#  config: classpath:logback-dev.xml

spring.datasource:
  url: jdbc:mysql://localhost:3306/alone
  username: root
  password: westos
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.:
  properties.hibernate.hbm2ddl.auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true